# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_hall_stat <- function(x, y, m) {
    .Call(`_MonotonicityTest_get_hall_stat`, x, y, m)
}

